### ISSUE TITLE
How to draw the Figure 3 about ACF?

### ISSUE THREAD

**Issue by yizhicainiao2022** [hanlu-nju/channel_independent_MTSF#2]
Hello, Lu Han.

I want to draw the ACF curve about ETTm2 dataset, so I reproduce the ACF code from equation (5). But I found that it's different between figure 3 (a) and what i drawed.

so I want to ask you whether you  can release your acf_plot code?

thanks.

The following is my acf code: 

```
  def single_channel_acf(series, max_offset=50):
      result = []
      series = series.squeeze()
      mu = np.mean(series)
      div_term = np.mean([(x - mu) ** 2 for x in series])
  
      for offset in range(max_offset):
          series_len = series.shape[0]
          valid_length = series_len - offset
          numerator = np.mean([(series[i] - mu) * (series[i + offset] - mu) for i in range(valid_length)])
          result.append(numerator / div_term)
      return result

**Comment by hanlu-nju** [comment]
The ACFs were computed by using `acf` function in `statsmodels.tsa.stattools`.  We call the function with the default arguments like `acf(series,n_lags)`.

**Comment by yizhicainiao2022** [comment]
thank you.
